[package]
name = "scale"
version = "0.1.0"
edition = "2024"

[lib]
name = "scale"
path = "lib.rs"

[features]
python_plugins = ["test_rig/python_plugins"]

[dependencies]
test_rig = { path = "../.." } 