[package]
name = "connect"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
mysql = { version = "26.0", features = ["chrono"] }
rpassword = "7.2"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }

[[example]]
name = "simple_multi_connection"
path = "examples/simple_multi_connection.rs"
required-features = []

[[example]]
name = "multi_connection_example"
path = "examples/multi_connection_example.rs"
required-features = []